services:
  fastapi:
    build: .
    volumes:
      - ./qr_codes:/myapp/qr_codes
      - ./:/myapp/
    environment:
      - QR_CODE_DIR=./qr_codes
      - FILL_COLOR=red
      - BACK_COLOR=white

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./qr_codes:/var/www/qr_codes
